from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware

from .caption_service import CaptionService

app = FastAPI(
    title="Image Caption Generator",
    description="Uploads an image and returns a caption generated by the experiment 3 model.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

caption_service = CaptionService()


@app.get("/health")
def health_check() -> dict:
    return {"status": "ok"}


@app.post("/generate-caption")
async def generate_caption(image: UploadFile = File(...)) -> dict:
    if not image.content_type or not image.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Please upload a valid image file.")

    image_bytes = await image.read()
    if not image_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    try:
        caption = caption_service.generate_caption(image_bytes)
    except Exception as exc:  # pragma: no cover - surface error to client
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    return {"caption": caption}

